# Generated by Django 5.2.9 on 2025-12-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='layout_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
